### ISSUE TITLE
Gedit 3 now supports only python3 plugins

### ISSUE THREAD

**Issue by aciapetti** [dfuenzalida/gedit-git-branch-statusbar#3]
In the new Gedit 3 only python3 plugins are supported.
Enabling git-branch-statusbar plugin now produces the error:
WARNING **: Could not find loader 'python' for plugin "git-branch-statusbar"

Can you please update the plugin to make it work on the Gedit version included in Ubuntu 18.04 LTS?

Thanks Andrea

**Comment by dfuenzalida** [comment]
Hi Andrea, thanks for reporting this issue and I'm glad it is (or was) useful to you. However, as you can see, I haven't touched this repo in ages (since late 2011!). Would you be interested in cloning the repo and sending me a pull request?

I had a quick look and maybe all that needs to be changed is adding a line at the top of the file as in this StackOverflow answer: https://stackoverflow.com/a/19305076

**Comment by aciapetti** [comment]
Hi Denis, thanks for the quick reply. I'll try to check it during the weekend. Hope of being able to do so.

**Comment by dfuenzalida** [comment]
OK, it seems I was able to figure the things I needed to update for it to work on Ubuntu 18.04:

* Change the launcher configuration
* Install `python3-git` and `gettext` instead of the previous libs
* Handle some Python3 specifc changes (call `str` instead of expect coercion to Strings)

I'll push my changes shortly, here's a screenshot from my laptop:

![gedit-ubuntu-18](https://user-images.githubusercontent.com/208068/55204500-6c8d9480-518c-11e9-872e-cbff1249ee13.png)

**Comment by dfuenzalida** [comment]
It seems that should do. Please try it on your computer and let me know if it works. Sorry for just going ahead before you tried!

On the other hand, if you find this plugin to be useful, and want to make UX improvements (eg. the label could be prettier, maybe getting rid of that border, or maybe using some padding) you are more than welcome to contribute.

**Comment by aciapetti** [comment]
Thanks a lot, Denis. It's working nicely now! 
On my company repositories, it's not detecting the git branch, though.
Do you have any idea why?
See images attached.

![git_branch](https://user-images.githubusercontent.com/704205/55229111-5c24fa80-521c-11e9-9a39-d5887091de29.png)

![no_branch_here](https://user-images.githubusercontent.com/704205/55229133-69da8000-521c-11e9-8b1d-ac7d74f40a40.png)

**Comment by aciapetti** [comment]
Perhaps we can add some other simple info, like the status of the repository (are there changed or untracked files? use different colors for different situations...) and a simple icon for git branches.
Obtaining the info is pretty simple:
print('Repo is in dirty status {}'.format(repo.is_dirty()))
print('Repo untracked files {}'.format(len(repo.untracked_files)))
print('Repo changed files {}'.format(len(repo.index.diff(None))))
Icons:
![git-branch](https://user-images.githubusercontent.com/704205/55238290-6bb03d80-5234-11e9-8002-c2057d2284bc.png)
![git-tree](https://user-images.githubusercontent.com/704205/55238291-6bb03d80-5234-11e9-8645-635d67ccb263.png)

Something like this:
![panel](https://user-images.githubusercontent.com/704205/55238766-964ec600-5235-11e9-9928-af935fa7815e.png)

WDYT?

**Comment by dfuenzalida** [comment]
> On my company repositories, it's not detecting the git branch, though.
> Do you have any idea why?

I guess what's happening is that the plugin only looks in the directory of the current file being edited, but not recursively, so if you edit a file like `<project-root>/dir1/myfile.txt` it won't work. I'll take a look at that this weekend.

**Comment by aciapetti** [comment]
Yes. You're right.
Try git_repo = git.Repo(dir_path, search_parent_directories=True) instead of repo = git.Repo(dir_path).

**Comment by dfuenzalida** [comment]
Yes, using `search_parent_directories=True` did the trick:

![gedit-subdirs](https://user-images.githubusercontent.com/208068/55282052-c8296080-52f9-11e9-8d39-0f4f14a2d962.png)

@aciapetti I've pushed this change to the repo in the latest commit b8f59c0d10f1f0aad3392c3f210925e78b6c9c7e ... please confirm if it works on your company repos.

For handing the UI enhancements, I'll create a separate issue and some links to the Python-gtk3 tutorial so we can how feasible would be to include a Git logo in the status bar, etc.

**Comment by aciapetti** [comment]
Thanks a lot @dfuenzalida, the plugin is now working perfectly on each case I've tested. I think you can close this issue. Thanks again for the prompt reply and for the wonderful collaboration. I'll contact you via mail directly on GMail to show you my small steps forward in the issue #4
